# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170908_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='hashing_rate',
            field=models.OneToOneField(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Hashing_Rate'),
            preserve_default=False,
        ),
    ]
