# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gpu_hashing_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='tdp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='power_supply',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bitcoin_value',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
