# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170909_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Power_Supply',
            new_name='PS',
        ),
    ]
