# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170923_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bitcoin_Value',
            new_name='BitcoinValue',
        ),
        migrations.RenameModel(
            old_name='Hashing_Rate',
            new_name='HashingRate',
        ),
    ]
